import path from "path";
import fs from "fs-extra";
import chalk from "chalk";
import ora from "ora";
import { execa } from "execa";
import { REGISTRY, COMPONENTS_BY_NAME } from "../registry";

interface AddOptions {
  dir?: string;
  overwrite?: boolean;
  install?: boolean;
}

export async function add(components: string[], options: AddOptions = {}) {
  const cwd = process.cwd();

  if (!components || components.length === 0) {
    console.log(chalk.red("\n  Error: Specify at least one component.\n"));
    console.log(`  ${chalk.dim("Example:")} ${chalk.cyan("npx atlasui add button card modal\n")}`);
    process.exit(1);
  }

  // ─── Resolve component + dependencies ─────────────────────────────────────

  const toInstall = new Set<string>();

  function resolveComponent(name: string) {
    const normalized = name.toLowerCase().replace(/([a-z])([A-Z])/g, "$1-$2").toLowerCase();
    const meta = COMPONENTS_BY_NAME.get(normalized) || COMPONENTS_BY_NAME.get(name);
    if (!meta) {
      console.error(chalk.red(`\n  Component not found: "${name}"\n`));
      console.log(`  Run ${chalk.cyan("npx atlasui list")} to see available components.\n`);
      return;
    }
    toInstall.add(meta.name);
    meta.registryDeps?.forEach((dep) => resolveComponent(dep));
  }

  components.forEach(resolveComponent);

  if (toInstall.size === 0) return;

  // ─── Load config ──────────────────────────────────────────────────────────

  const configPath = path.join(cwd, "atlas.config.json");
  const config = fs.existsSync(configPath)
    ? fs.readJsonSync(configPath) as { aliases?: { components?: string } }
    : null;

  const aliasedDir = config?.aliases?.components?.replace(/^@\//, "");
  const targetDir = path.join(cwd, options.dir ?? aliasedDir ?? "components/ui");

  console.log(
    chalk.bold.blue("\n  AtlasUI Add\n") +
    chalk.dim(`  Adding ${[...toInstall].join(", ")}...\n`)
  );

  // ─── Collect all npm deps ──────────────────────────────────────────────────

  const allNpmDeps = new Set<string>();
  for (const name of toInstall) {
    const meta = COMPONENTS_BY_NAME.get(name)!;
    meta.deps.forEach((d) => allNpmDeps.add(d));
  }

  // ─── Copy component files ──────────────────────────────────────────────────

  // real usage files would be fetched from the registry server.
  // we write stubs that import from @atlasui/core.

  for (const name of toInstall) {
    const meta = COMPONENTS_BY_NAME.get(name)!;
    const spinner = ora(`Adding ${chalk.bold(name)}`).start();

    const kebabName = name;
    const pascalName = name.split("-").map((p) => p[0].toUpperCase() + p.slice(1)).join("");

    const destDir = path.join(targetDir, kebabName);
    await fs.ensureDir(destDir);

    const destFile = path.join(destDir, "index.tsx");

    if (fs.existsSync(destFile) && !options.overwrite) {
      spinner.warn(chalk.yellow(`${name} already exists (use --overwrite to replace)`));
      continue;
    }

    // write a re-export stub — in real usage this copies the full source
    const stub = generateComponentStub(pascalName, kebabName, meta.category);
    await fs.writeFile(destFile, stub);

    spinner.succeed(chalk.green(`Added ${name} → ${path.relative(cwd, destFile)}`));
  }

  // ─── Install npm dependencies ──────────────────────────────────────────────

  if (options.install !== false && allNpmDeps.size > 0) {
    const pm = detectPackageManager(cwd);
    const depsSpinner = ora(`Installing ${allNpmDeps.size} dependencies...`).start();

    try {
      const deps = [...allNpmDeps];
      const cmd = pm === "npm" ? ["npm", "install", ...deps] :
                  pm === "pnpm" ? ["pnpm", "add", ...deps] :
                  pm === "bun" ? ["bun", "add", ...deps] :
                  ["yarn", "add", ...deps];
      await execa(cmd[0], cmd.slice(1), { cwd });
      depsSpinner.succeed(chalk.green(`Installed: ${deps.join(", ")}`));
    } catch {
      depsSpinner.warn(chalk.yellow("Auto-install failed. Install manually:"));
      console.log(chalk.dim(`  npm install ${[...allNpmDeps].join(" ")}`));
    }
  }

  // ─── Done ─────────────────────────────────────────────────────────────────

  console.log(`
${chalk.bold.green("  ✓ Done!")} Components added to ${chalk.cyan(path.relative(cwd, targetDir))}

  ${chalk.dim("Import example:")}
  ${chalk.cyan(`import { ${[...toInstall].map((n) => n.split("-").map((p) => p[0].toUpperCase() + p.slice(1)).join("")).join(", ")} } from "@/components/ui/${[...toInstall][0]}"`)}
`);
}

function generateComponentStub(pascalName: string, kebabName: string, category: string): string {
  return `/**
 * AtlasUI — ${pascalName}
 *
 * This file was generated by the AtlasUI CLI.
 * You own this file. Edit it freely.
 *
 * @see https://github.com/JohnDev19/AtlasUI/${kebabName}
 */

// Re-export from @atlasui/core — or copy the full source here to customize.
export { ${pascalName} } from "@atlasui/core";
export type { ${pascalName}Props } from "@atlasui/core";
`;
}

function detectPackageManager(cwd: string): string {
  if (fs.existsSync(path.join(cwd, "bun.lockb"))) return "bun";
  if (fs.existsSync(path.join(cwd, "pnpm-lock.yaml"))) return "pnpm";
  if (fs.existsSync(path.join(cwd, "yarn.lock"))) return "yarn";
  return "npm";
}
